title: "slinkin-tech"
description: "Network software: network traffic analysis, internet service classification, metadata extraction"
keywords: dpi, deep packet inspection, traffic classification, nta, network traffic analyzer, integration solution, network monitor, dpi framework, dpi library, dpi engine, industrial dpi, sl dc engine, dc engine
baseurl: ""
url: "https://slinkin.tech"

#

common_dir: &common_dir
  - _includes
  - data/changelog

include:
  - _pages
  - _pages/tech/
  - _pages/tech/info/
  - data/changelog

#

defaults:
  - scope:
      path: ""
    values:
      image: "/assets/img/logo.png"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

logo: assets/img/favicon.png
#

header_pages:
  - _pages/index.md
  - _pages/dc_engine.md
  - _pages/blog.md
  - _pages/about.md
  - _pages/tech.md

#

style: light # dark (default), light, hacker, or nord
#listen_for_clients_preferred_style: true
disable_google_fonts: true

#
footer: '© 2020-2026 slinkin-tech: <a href="mailto:info@slinkin.tech">email</a>, <a href="/tech">tech</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console